[package]
name = "rust-spiffe"
version = "0.1.0"
authors = ["Max Lambrecht <maxlambrecht@gmail.com>"]
edition = "2018"
license = "Apache-2.0"
categories = ["crytography"]
keywords = ["SPIFFE", "X509", "JWT"]
readme = "README.md"
repository = "https://github.com/maxlambrecht/rust-spiffe"
description = "Rust client library implementation for SPIFFE"

[dependencies]
grpcio = { version = "0.6", default-features = false, features = ["protobuf-codec"] }
protobuf = "2.23.0"
futures = "0.3.15"
url = "2.2.2"
http = "0.2.4"
asn1 = { package = "simple_asn1", version = "0.5.3" }
thiserror = "1.0.25"
x509-parser = "0.9.2"
pkcs8 = "0.6.1"
zeroize = { version = "1.3.0", features = ["zeroize_derive"] }
jsonwebtoken = "7.2.0"
jsonwebkey = { version = "0.3.2", features = ["jsonwebtoken", "jwt-convert"] }
serde = { version = "1.0.126", features = ["derive"] }
serde_json = "1.0.64"
chrono = { version = "0.4.19", features = ["serde"] }

[build-dependencies]
protoc-grpcio = "3.0.0"

[dev-dependencies]
jsonwebkey = { version = "0.3.2", features = ["generate"] }
# used to verify that the certificates bytes are parseable as OpenSSL X.509 certificates.
openssl = "0.10.34"
